### ISSUE TITLE
How to run lora with SD models with API?

### ISSUE THREAD

**Issue by lanyusan** [replicate/replicate-python#101]
Is it supported? If yes, how? Can you provide an example?

Thanks.

**Comment by mattt** [comment]
Hi @lanyusan. We have instructions for running LoRA Inference model with Stable Diffusion on the Replicate model's page, [in the API tab](https://replicate.com/cloneofsimo/lora/api) (click "Python"):

```python
import replicate
output = replicate.run(
    "cloneofsimo/lora:fce477182f407ffd66b94b08e761424cabd13b82b518754b83080bc75ad32466",
    input={"prompt": "a photo of <1> riding a horse on mars"}
)
print(output)
```
