### ISSUE TITLE
error caused by difference in prediction version in webhook vs prediction payload

### ISSUE THREAD

**Issue by carlpeaslee** [replicate/replicate-python#111]
Original post from Slack:

<img width="729" alt="image" src="https://github.com/replicate/replicate-python/assets/15232222/a5f79fd9-d950-4549-bc92-9b0599d4b6aa">

https://replicatehq.slack.com/archives/C04AXJ6BR34/p1687821981253489

This was resolved temporarily with this workaround:

```
from replicate.prediction import Prediction as OriginalPrediction
from pydantic import Field
```
```
class Prediction(OriginalPrediction):
    version: str = Field(..., description="Version field")

```

thanks @anotherjesse for the help here.

**Comment by mattt** [comment]
Thanks for reporting, @carlpeaslee. This should have been fixed by #193 / [0.18.1](https://github.com/replicate/replicate-python/releases/tag/0.18.1), which changed `Prediction.version` to be a `str`.
