### ISSUE TITLE
"error 3 validation errors for Prediction" when running "replicate.run()"

### ISSUE THREAD

**Issue by waelmansourx** [replicate/replicate-python#112]
Everytime I use this command, with any model
```py
replicate.run(
        "stability-ai/stable-diffusion:<api-code>",
        input={"prompt": "a 19th century portrait of a wombat gentleman"}
    )
```
I recieve this error:
```bash
Field required [type=missing, input_value={'id': ''}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.1/v/missing
```

**Comment by Mig29github** [comment]
got the same error

**Comment by SCUTlihaoyu** [comment]
It should be the problem of updating the pydantic package to 2.0.Just reinstall version 1.9 will fix it. such as:
```
pip install pydantic==1.9
```

**Comment by waelmansourx** [comment]
@SCUTlihaoyu This worked well. Thank you!

**Comment by mattt** [comment]
Hi @waelmansourx. Thanks for reporting this. Apologies for the inconvenience. As @SCUTlihaoyu mentioned, these are due to breaking changes in [Pedantic 2.0](https://pypi.org/project/pydantic/2.0/) which was released a few days ago.

I'm looking into what it'd take to support both 1.x and 2.0. But in the meantime, pinning to 1.9 as @SCUTlihaoyu suggested should do the trick.

**Comment by mattt** [comment]
@waelmansourx @Mig29github @SCUTlihaoyu I just released [version 0.8.4](https://pypi.org/project/replicate/0.8.4/), which pins Pydantic to 1.x. This should solve the immediate problem you encountered with Pydantic 2 incompatibility.

As mentioned in #113, my goal is to update this library to support both Pydantic 1.x and 2.x in a future release.

Please let me know if you have any other issues with this. Thanks!

**Comment by simonw** [comment]
From https://pypi.org/project/pydantic/2.0/

> Pydantic V2 also ships with the latest version of Pydantic V1 built in so that you can incrementally upgrade your code base and projects: `from pydantic import v1 as pydantic_v1`.

**Comment by mattt** [comment]
@simonw Thanks for pointing that out, and for #121. Curious that this V1 shim doesn't seem to be mentioned anywhere on https://docs.pydantic.dev/latest/.
