### ISSUE TITLE
REPLICATE_API_TOKEN usage question

### ISSUE THREAD

**Issue by Maxioflex** [replicate/replicate-python#114]
> i have a an issue it is something that start's new varnew var = replicate . run REPLICATE_API_TOKEN but when i run it it say's the REPLICATE_API_TOKEN is incorrect and it has a Syntax error

**Comment by mattt** [comment]
Hi @Maxioflex. Are you following the instructions under the [Authentication](https://github.com/replicate/replicate-python#authenticate) section of the README?
