### ISSUE TITLE
Is there any rate limit?

### ISSUE THREAD

**Issue by ghost** [replicate/replicate-python#119]
Is there any per-second rate limit for using replicate-python? I mean similar to what is explained [here](https://replicate.com/docs/reference/http#rate-limits) for HTTP API.
p.s: excuse me if my question isn't so related here, I didn't find a community or forum about Replicate. If you know some, please share the link to it. Thanks.

**Comment by mattt** [comment]
Replicate's Python client uses the HTTP API, and therefore has the same rate limits as that.

> I didn't find a community or forum about Replicate. If you know some, please share the link to it. Thanks.

You can find our discord server here: https://discord.gg/replicate
