### ISSUE TITLE
Can you explain `webhook`, `webhook_completed`, and `webhook_events_filter`?

### ISSUE THREAD

**Issue by ethank852** [replicate/replicate-python#125]
I see these three options in the source code: https://github.com/replicate/replicate-python/blob/ea0fe2cf5d331193bfdc6040c807b1c3eca90ba8/replicate/prediction.py#L87

can you explain what are the differences?

**Comment by mattt** [comment]
Hi @ethank852. We have a write-up of webhooks here :https://replicate.com/docs/webhooks#setting-webhooks

> To use webhooks, specify a `webhook` URL in the request body when creating a prediction.

> By default, Replicate sends requests to your webhook URL whenever there are new logs, new outputs, or the prediction has finished. You can change which events trigger a webhook using [the `webhook_events_filter` property](https://replicate.com/docs/reference/http#predictions.create--webhook_events_filter).

`webhook_completed` is a property on predictions that indicates whether all webhooks have finished sending.
