### ISSUE TITLE
Swagger/OpenAPI specification

### ISSUE THREAD

**Issue by HavenDV** [replicate/replicate-python#132]
Hey. We want to release an SDK for C# and would like to know if you have an official Swagger/OpenAPI spec? I did not find this in the documentation and when searching among the repositories of the organization
I think it would be great if this is available in a separate repository and updated according to the latest changes, like OpenAI - https://github.com/openai/openai-openapi

We have seen an unofficial C# SDK, but it was made for images and is not suitable for use with LLMs. Also, this was written by hand and it's more expensive to maintain, so we'd like to go through the auto-generate approach.

**Comment by mattt** [comment]
Hi, @HavenDV. Thanks for reaching out! Replicate's [API documentation](https://replicate.com/docs/reference/http) is [powered by an OpenAPI specification](https://replicate.com/docs/reference/http#openapi) that can be found at https://api.replicate.com/openapi.json.

Once you have something ready to share, we'd love to see what you come up with for a C# SDK. Feel free to @ mention me in this issue or email `team@replicate.com`.

**Comment by HavenDV** [comment]
@mattt Unfortunately your spec doesn't describe responses schemas. Perhaps you have a more complete specification (preferably in yaml)? Of course, we can add it ourselves, it will not take very much time, but I would like to avoid this (and refine the specification in the future after its changes)
