### ISSUE TITLE
Unable to pass `false` as input value to trainings.create

### ISSUE THREAD

**Issue by andreasjansson** [replicate/replicate-python#140]
The following example

```
training = replicate.trainings.create("stability-ai/sdxl:a00d0b7dcbb9c3fbb34ba87d2d5b46c56969c84a628bf778a7fdaec30b1b99c5", input={
    "input_images": "https://storage.googleapis.com/andreas-scratch-public/input-sprites.zip",
    "crop_based_on_salience": False,
}, destination="andreasjansson/sdxl-pixelart-sprites")
```

results in the following training:
<img width="935" alt="image" src="https://github.com/replicate/replicate-python/assets/713993/b6694e90-923a-4c16-bcd5-4b90411980f4">

Note that `crop_based_on_salience` is missing. If I set it to `True` it works as expected.

**Comment by mattt** [comment]
Hi @andreasjansson. This is actually a bug in how trainings are rendered on the Replicate website. If you fetch the training with the client, you should see that the `crop_based_on_salience` input is set to `False`.
