### ISSUE TITLE
Llama 2 outputs disjointed text 

### ISSUE THREAD

**Issue by michalkubizna** [replicate/replicate-python#143]
<img width="157" alt="Screenshot_2023-08-04_at_8 23 13_PM (1)" src="https://github.com/replicate/replicate-python/assets/51336870/e8c727f0-e0de-4ab3-a493-e658780471d9">

**Comment by mattt** [comment]
Hi @michalkubizna. Can you share some more information to help figure out what's happening? Which model / version of LLaMA are you using. Can you share the code that produced this? Can you share the ID of the prediction on Replicate?

**Comment by monshizadeh** [comment]
same here. here is the sample code:
import replicate

api_token = "my token"
client = replicate.Client(api_token=api_token)

while True:
    prompt = input("Enter your prompt (or 'exit' to quit): ")
    if prompt == "exit":
        break

    output = client.run(
        "replicate/llama-2-70b-chat:2c1608e18606fad2812020dc541930f2d0495ce32eee50074220b87300bc16e1",
        input={"prompt": prompt}
    )
    for item in output:
    print(item)

**Comment by mattt** [comment]
@monshizadeh Thanks. Can you please share the prediction ID so that I can see the raw output?

**Comment by mattt** [comment]
@monshizadeh @michalkubizna LLaMA and other LLMs generate models by [token](https://learn.microsoft.com/en-us/semantic-kernel/prompt-engineering/tokens). You can get a better idea about how words generally split into tokens in [this interactive demo](https://platform.openai.com/tokenizer).

The output of running LLaMA is an iterator or list of tokens. The reason why you're getting the results you are is that the Python `print` statement appends a newline by default. You can disable that by passing `end=""`:

```python
for token in output:
    print(token, end="")
```

**Comment by michalkubizna** [comment]
The problem is that it divides the individual words. For instance (refer to the attached photo), instead of printing "factually", it prints "fact" and "ually" separately. Similarly, for "Coherent", it displays "coh", "er", and "ent" as distinct segments. Please check the attached photo for reference.

**Comment by mattt** [comment]
@michalkubizna Yes, this is expected. LLaMA outputs by token, not word. It's hard to tell from a screenshot of text rather than text itself, but notice that "ually" doesn't have a leading space, like " fact", so if you were join with an empty string or print without a newline, everything would work as expected.

**Comment by michaecube** [comment]
Thanks. That makes sense.
