### ISSUE TITLE
How to get progress status of API calls?

### ISSUE THREAD

**Issue by 921kiyo** [replicate/replicate-python#152]
Hi Replicate team, 

I am using the replicate API for image generation and fine-tuning. In our front-end, we would like to show how much % of the job is complete, so users have a better idea of how much it's complete, how long it takes to complete etc (e.g 10%, 30% complete etc.). 

For image generation, I use `replicate.predictions.create` to start the image generation, and use the prediction id in `replicatepredictions.get(pred_id)`, to check the status. I am wondering if there's a way to calculate/estimate the completion progress using replicate API. I know that `Prediction.logs` shows some information about the progress, but it's all in string. 

I can do a hacky way to extract the progress from the logs, but let me know if there's a better way to calculate the progress (e.g how much of the iterations are complete out of XX total iterations etc).

**Comment by mattt** [comment]
Hi @921kiyo. Thanks so much for opening this issue.

Parsing logs is indeed the correct way to track the progress of a prediction as it's running. An affordance for this is provided in the [Go client library](https://github.com/replicate/replicate-go) and other libraries, but not Python — at least right now.

I just opened #155, which adds a `progress` property to `Prediction` that should do what you need. Please take a look and let me know what you think!

**Comment by mattt** [comment]
This is now available in [0.13.0](https://github.com/replicate/replicate-python/releases/tag/0.13.0).

**Comment by 921kiyo** [comment]
@mattt Thank you for much for adding this feature so quickly! I will try 0.13.0 to show the progress logs :)

**Comment by 921kiyo** [comment]
@mattt Just testing this new progress property. While it's working for vanilla SDXL model, `progress` property does not seem to be available for fine-tuned SDXL model (I've just fined tune a new model today by following https://replicate.com/blog/fine-tune-sdxl). I suspect if this is possibly a bug/edge case (or is this expected?).

**Comment by mattt** [comment]
@921kiyo Sorry for not responding sooner. I just replied to https://github.com/replicate/replicate-python/issues/171.
