### ISSUE TITLE
list the minimum required python version in the readme

### ISSUE THREAD

**Issue by yaronelh** [replicate/replicate-python#153]
It seems that replicate doesn't work on Python v3.6. It would be great to have an indication of what is the minimum version required on the instructions

**Comment by mattt** [comment]
Hi @yaronelh. Thanks for this feedback. Replicate works with any [supported version of Python](https://devguide.python.org/versions/#supported-versions) (3.8+), which is [indicated in `pyproject.toml`](https://github.com/replicate/replicate-python/blob/c1307caded150f805e4611cac1457c563acec5c5/pyproject.toml#L12). I also just opened https://github.com/replicate/replicate-python/pull/154, which puts this information in the README.

**Comment by yaronelh** [comment]
👍
