### ISSUE TITLE
ReplicateError: The specified version does not exist (or perhaps you don't have permission to use it?)

### ISSUE THREAD

**Issue by himmetozcan** [replicate/replicate-python#168]
I am trying to run the colab notebook example that is provided in readme page. I am always getting this error:
"ReplicateError: The specified version does not exist (or perhaps you don't have permission to use it?)"

I have tried changing the model version/name, api key and so but always same error. In my account I also have a credit card defined as the payment method. Can u help?

**Comment by mattt** [comment]
Hi @himmetozcan. This appears to be the same issue reported in https://github.com/replicate/replicate-python/issues/169. Please try setting your `REPLICATE_API_TOKEN` environment variable before importing the `replicate` package.
