### ISSUE TITLE
Delete a model

### ISSUE THREAD

**Issue by Jaquavious-Finkleton** [replicate/replicate-python#173]
Hi, I recently just started using Replicate and I'm working on fine-tuning models. However, does anyone know how to delete a model on the platform?

**Comment by donprasetiyo** [comment]
+1 for this.

**Comment by YouthDream0925** [comment]
I also want to know it. I saw the API docs of replicate and found a method to delete a model version. But there is no API to delete full model. How can I delete replicate model that created by API permanently?

**Comment by vpgits** [comment]
Did anyone find a way? Because I am seeing an unbilled charges piling up even though I don't have  active deployments

**Comment by chichoss** [comment]
+1

**Comment by satellitebryn** [comment]
Perhaps this: https://replicate.com/docs/reference/http#models.versions.delete

**Comment by sarfarazh** [comment]
I am facing the same issue. Has anyone found any solution to this?

**Comment by mattt** [comment]
Hey everyone. Sorry for not responding to this sooner. Replicate's API doesn't currently have an endpoint for deleting models. But as @satellitebryn correctly pointed out, it does have an endpoint for deleting model versions.

The Python client doesn't have a corresponding method for that API, and that was an oversight. I just opened https://github.com/replicate/replicate-python/pull/234, which resolves that.
