### ISSUE TITLE
How to create a model via API

### ISSUE THREAD

**Issue by unsanny** [replicate/replicate-python#174]
Hi, I just started to fine-tune model and do need to create a private model via replicate client or via API.
Issue here, I can see method related to model creation in repo but it raises NotImplementedException.
Question here is it possible to create a model via API or via any other approach rather than to create a model manually via browser?

**Comment by juliansci** [comment]
This would be really helpful.

**Comment by vanjos** [comment]
+1 for this please

**Comment by chloebarreau** [comment]
+1

**Comment by YouthDream0925** [comment]
+1

**Comment by mattt** [comment]
Hi everyone! I'm happy to say that, as of [0.16.0](https://github.com/replicate/replicate-python/releases/tag/0.16.0), you can now create models through Replicate's API and client libraries (#184). From the README:

> ## Create a model
> 
> You can create a model for a user or organization
> with a given name, visibility, and hardware SKU:
> 
> ```python
> import replicate
> 
> model = replicate.models.create(
>     owner="your-username",
>     name="my-model",
>     visibility="public",
>     hardware="gpu-a40-large"
> )
> ```

**Comment by harsh-patel-us** [comment]
But when I set visibility private then it will give me an error.

How do I fix them? Provide me suggestion.
