### ISSUE TITLE
can i download my model? 

### ISSUE THREAD

**Issue by legaltextai** [replicate/replicate-python#180]
if i fine tune on replicate , can i download it to my machine? i can't find the answer in the Docs. 
thanks

**Comment by mattt** [comment]
Hi @legaltextai. You can download the Docker image for any model you have access. Instructions for how to do that can be found in the API tab, under "Docker". For example, [here are the instructions for SDXL](https://replicate.com/stability-ai/sdxl/api?tab=docker). `docker run` will pull and run the image. If you just want to pull, replace with `docker pull` and omit everything but the image URI (host `r8.im`).

**Comment by legaltextai** [comment]
thank you much!
