### ISSUE TITLE
Pip install broken in 0.15.6

### ISSUE THREAD

**Issue by AaEll** [replicate/replicate-python#182]
Python 3.11.4 (main, Jul 25 2023, 17:36:13) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin

pip3 install replicate==0.15.6
python3
>> import replicate
ModuleNotFoundError: No module named 'replicate'

pip3 install replicate==0.15.5
python3
>> import replicate
>>replicate.run
<bound method Client.run of <replicate.client.Client object at 0x1008f7390>>

**Comment by mattt** [comment]
@AaEll Thanks so much for reporting this. I just reproduced it myself, so I'll go ahead and yank that release.

**Comment by mattt** [comment]
https://pypi.org/project/replicate/0.15.6/

<img width="212" alt="Screenshot 2023-11-02 at 09 07 54" src="https://github.com/replicate/replicate-python/assets/7659/a5ce6f05-dd08-4054-9998-69f8ab40171d">

**Comment by AaEll** [comment]
For sure! Thanks for the quick response and great product!

**Comment by mattt** [comment]
I think this may have been the cause: 

https://github.com/replicate/replicate-python/commit/39d6bc9756f6ac92fdfe95625846488bd8368090#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R33

**Comment by mattt** [comment]
#183 appears to have resolved the underlying problem. I just published [0.15.7](https://pypi.org/project/replicate/0.15.7/) with this change, and everything is working as expected for me.

Thanks again for reporting this, @AaEll 🙇
