### ISSUE TITLE
[Feature Request] Lower level model access 

### ISSUE THREAD

**Issue by AaEll** [replicate/replicate-python#185]
Hi,

I have an application that I need the token scores, and lower level access to \<eos\> and \<bos\> tokens.

If you have time, I would appreciate this implemented. Until then am I planning to use the huggingface https://api-inference.huggingface.co/models/bert-base-uncased for token scores

**Comment by mattt** [comment]
Hi @AaEll. What a model takes as input and provides as output depends on the implementation of the model itself. If you need something else that a given model isn't providing, you could try finding another model that has what you need, or — if it's open source — you could try forking your own version.
