### ISSUE TITLE
NameError: name 'pydantic' is not defined

### ISSUE THREAD

**Issue by EnkiEnil** [replicate/replicate-python#195]
[/usr/local/lib/python3.10/dist-packages/replicate/model.py](https://localhost:8080/#) in Model()
     24     """
     25 
---> 26     _client: "Client" = pydantic.PrivateAttr()
     27 
     28     url: str

NameError: name 'pydantic' is not defined

**Comment by mattt** [comment]
Hi @EnkiEnil. Thanks for reporting this. I think I understand the problem, and have a fix merged with https://github.com/replicate/replicate-python/pull/196. Working to cut a new release now.

**Comment by mattt** [comment]
This is now available in [0.18.1](https://pypi.org/project/replicate/0.18.1/)

**Comment by EnkiEnil** [comment]
Thank you!
