### ISSUE TITLE
Increase the timeout

### ISSUE THREAD

**Issue by smyja** [replicate/replicate-python#208]
Some models take up 6 minutes to get started.It would be better to add a timeout parameter to the run function to increase the timeout.

**Comment by mattt** [comment]
@smyja Sorry, by timeout are you referring to the polling interval? 

The `replicate.run` method creates a prediction and polls for updates until the prediction is complete. The initial call to create a prediction should complete quickly and return a prediction in `starting` status. And subsequent requests to get the latest status should also complete quickly, and not time out.

**Comment by Digvijay6** [comment]
Hi @smyja I wanted to know if `output = version.predict(input={"your_input": "value"}, timeout=timeout_value)`  works for the timeout issue or do I need to learn async_run.
