### ISSUE TITLE
document `replicate.models.predictions.create` method

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-python#212]
Followup to https://github.com/replicate/replicate-python/pull/207

**Comment by pavansai26** [comment]
@zeke  can i work on the above one

**Comment by zeke** [comment]
Thanks for the offer @pavansai26. I'm actually not sure about the state of this method in the Python API client. @mattt what do you think?

**Comment by mattt** [comment]
`replicate.models.predictions.create` has been deprecated in favor of an overload to `replicate.predictions.create` that accepts a `model` kwarg. This is documented in the README in this section: https://github.com/replicate/replicate-python?tab=readme-ov-file#run-a-model-and-stream-its-output
