### ISSUE TITLE
Uploading data from Google Drive

### ISSUE THREAD

**Issue by Dia1293** [replicate/replicate-python#218]
Hi, I'm trying to upload .zip file to train LoRa from Google Drive. However, documentation mentions I can do it, but I get error: 

    raise ModelError(prediction.error)
replicate.exceptions.ModelError: File is not a zip file

Example:
lora_url = replicate.run(
    "replicate/lora-training:b2a308762e36ac48d16bfadc03a65493fe6e799f429f7941639a6acec5b276cc",
input={"instance_data": "https://drive.google.com/file/d/1qW-nzIQCYRABI40GmjBB3V8gv6dr1giA/view?usp=drive_link", "task": "face"}
)

Same zip works just fine with other file-sharing service. By what other means zip file can be uploaded? upload_response doesn't work ether...

**Comment by mattt** [comment]
Hi @Dia1293. Curling that URL produces an HTML response:

```console
$ curl -i "https://drive.google.com/file/d/1qW-nzIQCYRABI40GmjBB3V8gv6dr1giA/view?usp=drive_link" | less 
content-type: text/html; charset=utf-8
x-robots-tag: noindex, nofollow, nosnippet
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: Mon, 01 Jan 1990 00:00:00 GMT
date: Sun, 10 Dec 2023 17:57:58 GMT
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
content-security-policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
referrer-policy: origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
server: GSE
set-cookie: NID=511=XtpWZd_ZgB6CJXaPzPdPppkMTrV94gJ4xr1H68pPJRWBZc4uZJQhMgSWy85Do8c2mpx5bSuXaMAV9kfOHinwN4pGnRFXqiUMWu4pOyxA0T-Ey6BVeUBTVSZB9QBta9Acj__Abb_ubcli8IHPvumsFwohorLMriE0cd6MqY2Ul1s; expires=Mon, 10-Jun-2024 17:57:58 GMT; path=/; domain=.google.com; HttpOnly
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
accept-ranges: none
vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
```

Opening the link in a browser may eventually result in downloading a Zip file, but the model needs a URL to the actual Zip file.
