### ISSUE TITLE
to have 4 channels, but got 5 channels instead

### ISSUE THREAD

**Issue by dinoglobal** [replicate/replicate-python#220]
I am going to erase the area with the following two files. However, an error keeps occurring. 

image file: https://d2dhsa6ilfcfin.cloudfront.net/sample/image.png
mask file : https://d2dhsa6ilfcfin.cloudfront.net/sample/image_mask.png

Error: Given groups=1, weight of size [64, 4, 7, 7], expected input[1, 5, 606, 806] to have 4 channels, but got 5 channels instead

**Comment by mattt** [comment]
Hi @dinoglobal. This looks like an error specific to the model you're using instead of the Python client library. If the model has a linked GitHub repo, you can try contacting the maintainers.
