### ISSUE TITLE
How to pass chat histories?

### ISSUE THREAD

**Issue by liebkne** [replicate/replicate-python#232]
For example, for model https://replicate.com/mistralai/mistral-7b-instruct-v0.1 , is the user required to format the whole chat histories into `prompt` param manually? Thanks.

**Comment by mattt** [comment]
Hi, @liebkne. Yes, you'll need to pass the previous chat history to the `prompt` input of the model. For long histories, you may need to perform summarization.

**Comment by liebkne** [comment]
Ah, thanks.
