### ISSUE TITLE
How to stay in queue when calling API Python

### ISSUE THREAD

**Issue by quocanh34** [replicate/replicate-python#236]
I have developed a model using Replicate. I've noticed that when I make consecutive API calls without a delay, the second call is processed immediately without needing to reload the model. However, if there is a gap of around one minute between calls, Replicate reloads the model for the next call, leading to a significant delay. 

Is there a way to keep the model loaded or stay in the queue for a certain amount of time to avoid this reloading process?

**Comment by mattt** [comment]
Hi, @quocanh34. Models on Replicate are automatically scaled up when you run them and scaled down after a period of inactivity. You can read more about that [in our docs](https://replicate.com/docs/how-does-replicate-work#cold-boots).

If you need better performance for your model, you can [create a deployment](https://replicate.com/docs/guides/deploy-a-custom-model#step-4-deploy-and-scale).
