### ISSUE TITLE
Return cost in minutes of inference

### ISSUE THREAD

**Issue by Wheest** [replicate/replicate-python#24]
Users have a finite number of minutes of inference per-month.

It would be useful to see how many compute minutes Replicate has charged for a given inference once it has completed.

This could be useful for allocating time to a given user, or simply profiling.

I've been looking at the code, and am not seeing anything that does this.  However it seems like something that could be a member of the [Prediction class](https://github.com/replicate/replicate-python/blob/main/replicate/prediction.py#L12).

**Comment by CEOSiyris** [comment]
I think is a great idea

**Comment by Mrchen116** [comment]
I strongly agree it a good idea. I really need it.

**Comment by antomin** [comment]
+

**Comment by krrishdholakia** [comment]
any updates on this?

**Comment by mattt** [comment]
As of #136, you can now get the predict time in seconds through the `metrics` field of a prediction.

```python
prediction.metrics['predict_time']
```
