### ISSUE TITLE
Pixray returns similar output regardless of prompt

### ISSUE THREAD

**Issue by Wheest** [replicate/replicate-python#25]
I am running the pixray model using the following code:

```python
import replicate
import requests


def save_image(url, filename):
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)


model = replicate.models.get("pixray/text2image")

i = 0
for image in model.predict(prompt="An old man eating a cake"):
    print(image)
    save_image(image, f"{i}.png")
    i += 1
```

However, I find that regardless of the prompt I give, the output is very similar, what appears to be the default "Cairo skyline at sunset." prompt.

The URLs of the generated images I print _are_ different between runs, and if I do a checksum of the images between runs (e.g. `$shasum 19.png`), the images are different.  However visually they look very similar.

Here is the final output for the prompt: "An old man eating a cake":
![21](https://user-images.githubusercontent.com/16022573/171222825-4007651b-624b-4ef8-bf65-60e3808f48af.png)

And here is the output for ""A poke of chips":
![21](https://user-images.githubusercontent.com/16022573/171223029-398d9f38-29b0-4411-aef2-76659ebca5e6.png)

I got the code for this inference from the "Run with API" tab of the https://replicate.com/pixray/text2image page.

**Comment by Wheest** [comment]
Thanks, I note that the README for the Python API uses the singular "prompt" for pixray, [see here](https://github.com/replicate/replicate-python/blob/main/README.md?plain=1#L32), which is where I believe the error was introduced.  I've added a patch for it.

However yes on the Pixray page the code is correct, see below:
![Screenshot_20220601_090155](https://user-images.githubusercontent.com/16022573/171356968-43eafc85-5a70-4725-8308-f89d8f094320.png)

Poke of chips successfully generated:
![24](https://user-images.githubusercontent.com/16022573/171359973-b7441450-5c53-4c9a-9d14-97823ef5f35c.png)

**Comment by bfirsh** [comment]
Nice. Glad to hear that's working, and thanks for the fix. I missed the example on the readme. We'll get better validation added.
