### ISSUE TITLE
How to upload weights in replicate ? 

### ISSUE THREAD

**Issue by tzktz** [replicate/replicate-python#250]
i want download weights stright from replicate...like this https://weights.replicate.delivery/default/SUPIR-v0Q.ckpt..

@zeke  @nickstenning @mattt

**Comment by tzktz** [comment]
i get it from replicate docs 👍

**Comment by RohitMidha23** [comment]
@tzktz can you point me to the relevant docs for the same?

**Comment by yelnady** [comment]
How is it to upload weights? @tzktz
