### ISSUE TITLE
Feature request: access to logs in the python API

### ISSUE THREAD

**Issue by johny-b** [replicate/replicate-python#251]
Right now `run` function returns only `prediction.output` (https://github.com/replicate/replicate-python/blob/43f75c756b5e2bb81235e93798fd7272b98ff5fe/replicate/run.py#L27-L63). 

I would like to also access `prediction.logs`. One trivial solution is to have something like `create_prediction` that would have all the logic in `run` except for waiting and returning only output, and `run` would internally call `create_prediction`.

Does that make sense? If yes, would you be open to a PR that adds this?

**Comment by alt1o** [comment]
I also want to get more information, like metrics. So I think maybe just returning all responses is a good choice.

**Comment by alt1o** [comment]
> I also want to get more information, like metrics. So I think maybe just returning all responses is a good choice.

I got it. Use `replicate.predictions.create` instead of `replicate.run`.

**Comment by johny-b** [comment]
Yeah, I can do this, but is this supposed to be a stable/public interface?

**Comment by mattt** [comment]
Hi @johny-b. You can access a prediction's logs through it's `logs` property. From the [README](https://github.com/replicate/replicate-python?tab=readme-ov-file#run-a-model-in-the-background)

```python
>>> prediction = replicate.predictions.create(
    version="(your model version)",
    input={"prompt":"Watercolor painting of an underwater submarine"})

>>> prediction
Prediction(...)

>>> prediction.wait()

>>> prediction.status
'succeeded'

>>> print(prediction.logs)
iteration: 0, render:loss: -0.6171875
iteration: 10, render:loss: -0.92236328125
iteration: 20, render:loss: -1.197265625
iteration: 30, render:loss: -1.3994140625

>>> prediction.output
'https://.../output.png'
```
