### ISSUE TITLE
Retry on all 5xx errors

### ISSUE THREAD

**Issue by parikls** [replicate/replicate-python#261]
Sometimes we are observing an `JSONDecodeError` raised by the library. 
This happens when replicate API returns `502 Bad Gateway`

httplib log:

```
https://api.replicate.com/v1/models/beautyyuyanli/multilingual-e5-large/versions/a06276a89f1a902d5fc225a9ca32b6e8e6292b7f3b136518878da97c458e2bad

{
http.fragment: ,
http.method: GET,
http.query: ,
http.response.status_code: 502,
reason: Bad Gateway
}
```

IMO retryable status codes should be extended to cover all possible `5xx` errors

https://github.com/replicate/replicate-python/blob/main/replicate/client.py#L203

**Comment by mattt** [comment]
Hi @parikls. It's not generally advisable to automatically retry on all 5XX responses, because most are not expected to succeed on subsequent requests. I can see the argument for 502, as it's sometimes returned for temporary problems, but I stand by our current behavior.

If you'd like different behavior, you can handle this error in a `try / except` block.

**Comment by parikls** [comment]
@mattt let's put a general 5xx retry question aside.

You already did a great job by integrating a retry mechanism in a lib, therefore as a library user I don't want to bother myself re-implementing retries in my own code. I want your library to be as simple as

```
await replicate.async_run('model-name', input=some_input)
```

Not sure I understand, if you are already aware about the 502 case, why that specific code is not retryable? Any specific reasons?
Even is there are so - as a library user I would expect to get more meaningful error subclassed from the `ReplicateException`, so my code can handle it properly and differentiate between unhandled errors and those which should be processed separately.

**Comment by mattt** [comment]
@parikls The thing about 502 errors is that they aren't a reliable indicator that retrying the request will succeed. It really depends on the specifics of how the API is being accessed (e.g. through a reverse proxy, VPN, or firewall).

I completely agree with you that a more specific error would be helpful. What we have right now is inadequate:

https://github.com/replicate/replicate-python/blob/a7f725c4685ec6039786ae43a1be8d30e6e8d3fa/replicate/client.py#L366-L368

I just opened https://github.com/replicate/replicate-python/pull/263, which I hope will make Replicate API errors more actionable. Please take a look and let me know what you think!

**Comment by parikls** [comment]
@mattt  thank you!
