### ISSUE TITLE
replicate.deployments.get fails

### ISSUE THREAD

**Issue by alxiang** [replicate/replicate-python#270]
We created a deployment of demucs (https://replicate.com/cjwbw/demucs) on Replicate a few weeks ago. We were on version 0.22.0 of the package, and the following code worked fine:

`replicate.deployments.get("pathstone-labs/lifelike-demucs")`

However, when we upload to version 0.25.0 of the package, we see the following error:

`
1 validation error for Deployment
current_release -> configuration -> scaling
  field required (type=value_error.missing)
`

So we are currently sticking to v0.22.0. Was there some kind of backwards incompatibility introduced in the recent versions of this package? Thanks.

**Comment by mattt** [comment]
Hi @alxiang. You're correct, this was a regression. I apologize for any inconvenience this caused. I just merged a fix for this in https://github.com/replicate/replicate-python/pull/271, which is now available in [0.25.1](https://github.com/replicate/replicate-python/releases/tag/0.25.1). Please let me know if you still see this or run into any other issues.
