### ISSUE TITLE
Using API to Enable/Disable Deployments in Scripts

### ISSUE THREAD

**Issue by talhen123** [replicate/replicate-python#282]
Hello,

I'm currently working on automating some of our processes and was wondering if it's possible to use an API to programmatically enable or disable deployments.

**Comment by mattt** [comment]
Hi @talhen123. Yes, you can use the Python client library to enable and disable deployments.

To disable a deployment, update with `min_instances` and `max_instances` set to 0:

```python
import replicate

replicate.deployments.update(
    deployment_owner="acme", 
    deployment_name="image-upscaler", 
    min_instances=0,
    max_instances=0
)
```

To enable a deployment, update `max_instances` to a value greater than 0:

```python
replicate.deployments.update(
    deployment_owner="acme", 
    deployment_name="image-upscaler", 
    max_instances=1
)
```
