### ISSUE TITLE
Getting destination as None. When training the model

### ISSUE THREAD

**Issue by kartikwar** [replicate/replicate-python#293]
Hi I am running this code: 
training = replicate.trainings.create(
    destination="kartikwar/business-card",
    model="stability-ai/sdxl",
    version="39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b",
    input={
      "input_images": "https://uploads.documents.cimpress.io/v1/uploads/94bc6c51-8cfc-4bbd-96fe-389facc3c0c5~122?tenant=furl",
      "token_string": "business card",
      "caption_prefix": "an image of business card",
      "max_train_steps": 1000,
      "use_face_detection_instead": False,
      "crop_based_on_salience": False
    }
)

When I check training.destination I get None. Can someone please check

**Comment by mattt** [comment]
Hi @kartikwar. Sorry to hear this isn't working as expected. Can you please go to your replicate.com dashboard, locate your training record, and share its ID?

**Comment by kartikwar** [comment]
Sure this is the ID sweb609nwsrgj0cf1xasrnmq3c. Seems like there is some issue with the zip file

**Comment by mattt** [comment]
Hi @kartikwar. As of [0.26.1](https://github.com/replicate/replicate-python/releases/tag/0.26.1), destination should no longer be `None` for successful trainings.
