### ISSUE TITLE
Can you upload local files to create training with sdxl?

### ISSUE THREAD

**Issue by Vadimkomis** [replicate/replicate-python#297]
I know that you can reference 'input_images` for public URL, but I wanted to see if it's possible to upload a list of images that are zipped to create training? When I tried it, I kept getting the following errors:

`Prediction input failed validation: {"detail":[{"loc":["body","input","input_images"],"msg":"'' is not a valid URL scheme. 'data', 'http', or 'https' is supported.","type":"value_error"}]}`

`Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "train.py", line 142, in train
input_dir = preprocess(
File "/src/preprocess.py", line 111, in preprocess
assert False, "input_images_filetype must be zip or tar"
AssertionError: input_images_filetype must be zip or tar`

`Prediction input failed validation: {"detail":[{"loc":["body","input","input_images"],"msg":"'file' is not a valid URL scheme. 'data', 'http', or 'https' is supported.","type":"value_error"}]}`

**Comment by Vadimkomis** [comment]
I realized that you can, so I'm closing this issue.

**Comment by abdul7235** [comment]
how?

**Comment by abdul7235** [comment]
### **Solution**


**I was able to solve it after a day long effort.** 

Here is how I was able to send local zip file for training:
```
   filename = "images.zip"
   with open(f"{filename}", "rb") as file_input:
        encoded_data = base64.b64encode(file_input.read())


    encoded_data_str = encoded_data.decode('utf-8')

    


    training = replicate.trainings.create(
        model="stability-ai/sdxl",
        version="7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
        input={
            "input_images": f"data:application/zip;base64,{encoded_data_str}",
            "token_string": "TOK",
            "caption_prefix": "a photo of TOK",
            "max_train_steps": 1000,
            "use_face_detection_instead": False
        },
        destination=f"{OWNER}/{model_name}"
    )
```

**Comment by winterdelta** [comment]
According to the Replicate Support AI Chat, just need to use a `URL` for the `input_images` `.zip`:

```
import replicate

# Create a new training
training = replicate.trainings.create(
    model="stability-ai/sdxl",
    version="your_model_version",
    input={
        "input_images": "https://your-domain.com/training-images.zip",
        # Other input parameters as needed
    },
    destination="your-username/your-model-name"
)

```

**Comment by richasempire** [comment]
> filename = "images.zip"
>    with open(f"{filename}", "rb") as file_input:
>         encoded_data = base64.b64encode(file_input.read())
> 
> 
>     encoded_data_str = encoded_data.decode('utf-8')
> 
>     
> 
> 
>     training = replicate.trainings.create(
>         model="stability-ai/sdxl",
>         version="7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
>         input={
>             "input_images": f"data:application/zip;base64,{encoded_data_str}",
>             "token_string": "TOK",
>             "caption_prefix": "a photo of TOK",
>             "max_train_steps": 1000,
>             "use_face_detection_instead": False
>         },
>         destination=f"{OWNER}/{model_name}"
>     )

You are amazing!
