### ISSUE TITLE
setup timeout without meaningful logs

### ISSUE THREAD

**Issue by afpro** [replicate/replicate-python#298]
my model keep failing setup with 'model container failed to boot and complete setup within 600 seconds'.
searched on google, no solution found.
how could I find more information about what happened?

**Comment by afpro** [comment]
model version: dea48a520fc0954407bfb1dd9dd3d8d4eabdb675b2cd947d6aaf302485a714ce

**Comment by mattt** [comment]
Hi @afpro. It looks like your model was configured to run on a T4. If the model is indeed 13B (as the name implies), the 16GB VRAM available on that hardware may not be sufficient. That'd be my guess as to why it's failing during setup. Go to the model settings and try switching the hardware to an A40 or A100.

**Comment by afpro** [comment]
> Hi @afpro. It looks like your model was configured to run on a T4. If the model is indeed 13B (as the name implies), the 16GB VRAM available on that hardware may not be sufficient. That'd be my guess as to why it's failing during setup. Go to the model settings and try switching the hardware to an A40 or A100.

I use llama2-chat-70b on A40 and got a 'out of memory' error, in this situation, i will got a python exception stack, not 'timeout'.

**Comment by afpro** [comment]
I just give up.

**Comment by Clement-Lelievre** [comment]
<img width="1478" alt="Image" src="https://github.com/user-attachments/assets/8c14432f-5f3a-4659-b8bb-e66d61718f8f" />

getting the same log, while the setup usually takes 30 seconds on the v40 of my model, any idea why?
