### ISSUE TITLE
model container failed to boot and complete setup within 600 seconds

### ISSUE THREAD

**Issue by christopher5106** [replicate/replicate-python#307]
Hi,

We are currently experiencing boot error while our code has not changed?!

We don't have much information except "model container failed to boot and complete setup within 600 seconds"

What could be the issue ? The built docker runs well locally. The issue is not always persistent.

**Comment by erbridge** [comment]
Please contact support for help with your specific model: https://replicate.com/support

**Comment by christopher5106** [comment]
Support has been contacted earlier this morning, issue is still not solve. And What about such an error message without more clues, without log,

**Comment by christopher5106** [comment]
It should be planned asap to have more explicit error messages

**Comment by christopher5106** [comment]
Thanks for the update with the setup logs! That's a very good news.

Your communication on Github should be improved, I just discovered it this morning.

**Comment by mattt** [comment]
Hi @christopher5106. Sorry we didn't do a great job helping you out here. It sounds like the setup logs on replicate.com gave you the information you needed to solve your problem. Was there anything else we can help you with?

**Comment by christopher5106** [comment]
@mattt after discussion with my team, we are not sure the setup logs were there before, because we gave attention to them only after we got machines not booting at all:

`model container failed to boot and complete setup within 600 seconds`

As you can see, yesterday, while your [status page](https://replicatestatus.com/incidents) was totally fine with green flags, we were unable to start any prediction for the day of yesterday

![image](https://github.com/replicate/replicate-python/assets/6875375/c209541a-82ea-412d-b2c3-4bae13fc28d4)
![image](https://github.com/replicate/replicate-python/assets/6875375/62e19c8e-05d0-4b00-a312-e5755426eecb)

We don't know what we should do we see the message 


`model container failed to boot and complete setup within 600 seconds`

because it's explicit enough to take action for us.

**Comment by christopher5106** [comment]
I sent you by PM over X half a dozen versions we published for which there were a few dozen boot failures.

**Comment by mattt** [comment]
@christopher5106 Thanks for your patience. I escalated internally, and our customer support engineer has responded to your ticket. I'll let them take it from there.

**Comment by christopher5106** [comment]
Thanks!
