### ISSUE TITLE
Training failed.  Failed to create trained image after successful training run.

### ISSUE THREAD

**Issue by khenzo** [replicate/replicate-python#308]
Hi,
after a pair of successful training (SDXL), all my trainings are ending with this message: "Training failed. Failed to create trained image after successful training run." 

I've tried to create a new destination model and create a new API Token to start the creation using the Nodejs Client Library. 
I've started a dozen of trainings using the web interface but the response is always the same.

Can someone please have a look into this?

Thank you very much!

**Comment by mattt** [comment]
Hi @khenzo. Can you please share a link to a failed training? Any code you can share would also be helpful for understanding what the problem might be.

**Comment by mattt** [comment]
Closing this for now. Happy to reopen if you can share more information to troubleshoot this.

**Comment by MaryBIZCO** [comment]
HI
I HAVE THE SAME PROBLEM
ANY ADVICE PLEASE

**Comment by MaryBIZCO** [comment]
Training failed.

Prediction input failed validation: {"detail":[{"loc":["body","input","images"],"msg":"'' is not a valid URL scheme. 'data', 'http', or 'https' is supported.","type":"value_error"}]}

**Comment by MaryBIZCO** [comment]
{
  "completed_at": "2024-10-20T18:23:35.925477Z",
  "created_at": "2024-10-20T18:23:35.920000Z",
  "data_removed": false,
  "error": "Prediction input failed validation: {\"detail\":[{\"loc\":[\"body\",\"input\",\"images\"],\"msg\":\"'' is not a valid URL scheme. 'data', 'http', or 'https' is supported.\",\"type\":\"value_error\"}]}",
  "id": "9es8e34zy1rj20cjncns14fny4",
  "input": {
    "steps": 1000,
    "images": "marymway",
    "repo_id": "marymway/flux.1-dev-lora",
    "hf_token": "[REDACTED]",
    "batch_size": 1,
    "model_name": "marymway/flux.1-dev",
    "resolution": "512,768,1024",
    "lora_linear": 16,
    "learning_rate": 0.0004,
    "lora_linear_alpha": 16
  },
  "logs": null,
  "metrics": {
    "total_time": 0.005477
  },
  "output": null,
  "started_at": "2024-10-20T18:23:35.925477Z",
  "status": "failed",
  "urls": {
    "get": "https://api.replicate.com/v1/trainings/9es8e34zy1rj20cjncns14fny4",
    "cancel": "https://api.replicate.com/v1/trainings/9es8e34zy1rj20cjncns14fny4/cancel"
  },
  "version": "06e50f60983aa9ad9e4c13ba1d56ee235925ee6bd1c604d94c26a3322aeb8d47"
}
