### ISSUE TITLE
Replicate.predictions.create failing for bytedance/sdxl-lightning-4step

### ISSUE THREAD

**Issue by hershalb** [replicate/replicate-python#320]
Running: ```pred = replicate.predictions.create(model="bytedance/sdxl-lightning-4step", input={"prompt": "a jaguar eating a lion"})```

is returning ```detail: The specified version does not exist (or perhaps you don't have permission to use it?)```. Is there a new version that can't be used by the public? Is it possible to prevent these versions from being called when trying to use public models. Thanks

**Comment by mattt** [comment]
Hi @hershalb. Sorry you're having problems with this. Some models like [meta-llama-3](https://replicate.com/meta/meta-llama-3-8b) can be called by name. But most others, including `bytedance/sdxl-lightning-4step` are called with a version ID.

You can find example code for calling any model on its API tab: https://replicate.com/bytedance/sdxl-lightning-4step/api

```python
import replicate

input = {
    "prompt": "self-portrait of a woman, lightning in the background"
}

output = replicate.run(
    "bytedance/sdxl-lightning-4step:5f24084160c9089501c1b3545d9be3c27883ae2239b6f412990e82d4a6210f8f",
    input=input
)
print(output)
```
