### ISSUE TITLE
Prediction ID in exceptions?

### ISSUE THREAD

**Issue by rohan-mehta** [replicate/replicate-python#324]
Would it be possible to add the prediction ID in exceptions? Would help with debugging. Most interested in when it's a `ModelError`, but would be useful in all exceptions.

**Comment by placescoredata** [comment]
Hi @mattt , sorry for poking a closed issue. Just wanted to know if there's any reason the type for the new `prediction` property was enclosed in quotes? It prevents type hints from loading into the editor.

**Comment by mattt** [comment]
@placescoredata You're referring to this?

```python
from typing import TYPE_CHECKING, Optional

if TYPE_CHECKING:
    from replicate.prediction import Prediction

class ModelError(ReplicateException):
    prediction: "Prediction"
```

We use this pattern throughout the project to provide type hints without introducing circular imports. The `if TYPE_CHECKING` lets analysis tools resolve the `"Prediction"` forward reference. Type hints work for me in VSCode using Pylance (`ms-python.vscode-pylance`).

<img width="367" alt="Screenshot 2024-08-08 at 06 43 57" src="https://github.com/user-attachments/assets/180ffdfa-6c42-43fc-9aae-fe26b176c289">

What editor are you using? Do any of the other quoted forward references work for you?
