### ISSUE TITLE
SDK is missing Deployments.Delete

### ISSUE THREAD

**Issue by jlewi** [replicate/replicate-python#330]
I don't think the client library includes a routine to delete deployments.

https://github.com/replicate/replicate-python/blob/b0bbc048d93b567b7817d1928a9ca717403afa10/replicate/deployment.py#L25
FYI @mattt

**Comment by mattt** [comment]
Thanks for pointing this out, @jlewi. I opened a PR implementing this in #331.

**Comment by mattt** [comment]
This is now available in [0.31.0](https://github.com/replicate/replicate-python/releases/tag/0.31.0)
