### ISSUE TITLE
- Seed Parameter Not Respected in Image Generation

### ISSUE THREAD

**Issue by danilomaiaweb** [replicate/replicate-python#334]
Hello,

I am experiencing an issue with the seed parameter when using the Replicate API for image generation. It seems that the seed parameter is not being respected, as the images generated with the same seed value do not match.

Details:

Model Used: black-forest-labs/flux-schnell

API Call Example:

output = replicate.run(
    "black-forest-labs/flux-schnell",
    input={
        "seed": 123456,
        "prompt": "black forest gateau cake spelling out the words \"FLUX SCHNELL\", tasty, food photography, dynamic shot",
        "num_outputs": 1,
        "aspect_ratio": "1:1",
        "output_format": "jpg",
        "output_quality": 100
    }
)
print(output)

Issue Observed:

Generating multiple images with the same seed value results in different images.
Even with a single image generation request, the output varies despite using the same seed.
Expected Behavior:
The images generated with the same seed value should be identical to ensure reproducibility.

Actual Behavior:
The generated images are different even when the seed value is the same.

Additional Information:

I have verified the issue with different seed values and different prompts to ensure it is not related to other parameters.
The issue persists across multiple requests.
Could you please investigate this issue and provide guidance on how to ensure the seed parameter is respected in image generation?

Thank you for your assistance.

Best regards,
Danilo Maia
From Brazil - Fortaleza - CE

**Comment by LorenoWeb** [comment]
solved

**Comment by mattt** [comment]
Hi @danilomaiaweb. I'm sorry that was causing you problems. This seems to be an issue with the model rather than the Python client or API. It looks like this issue has since been resolved in the model, so please try again and let us know if you're still having this problem.
