### ISSUE TITLE
How to fix unclose SSLSocket warning on replicate.run()

### ISSUE THREAD

**Issue by adnanahmad84** [replicate/replicate-python#335]
When I close pyton server (using ctrl+c), replicate.run() returns following warning message on console 

sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=404, family=2, type=1, proto=0, laddr=('192.168.100.105', 4488), raddr=('104.26.4.130', 443)>

I have reviewed replicate API for any available function to close SSLSocket but didn't find any function. Here is sample code:

        input = {
                    "image": image_object,
                    "prompt": "describe this image"
                }
        
        output = replicate.run(
            REPLICATE_API_URL,
            input = input
        )
        
        return_data = ("".join(output))
        return return_data 

Any suggestion how can I fix this warning?

**Comment by mattt** [comment]
Hi, @adnanahmad84. That's expected behavior, or at least I don't think that you should be concerned by that warning. You may be able to silence that warning by wrapping your client usage with the `closing` context manager.

```python
from contextlib import closing
with closing(replicate.default_client) as client:
     replicate.run(...)
```
