### ISSUE TITLE
No such file or directory: '/tmp/outputs'

### ISSUE THREAD

**Issue by nikitalokhmachev-ai** [replicate/replicate-python#349]
I noticed that in some older models, whenever I try to run them (regardless of whether it's through an API or the website), I get the "No such file or directory" error:

Example models:
https://replicate.com/fofr/consistent-character

Error:
```No such file or directory: '/tmp/outputs'```

https://replicate.com/omniedgeio/face-swap

Error:
```No such file or directory: '/tmp/tmp84g63pkz/1726245680.webp'```

Is there any way to work around these?

**Comment by mattt** [comment]
Hi @nikitalokhmachev-ai. I'm sorry that you're having trouble getting those to run. Unfortunately, those errors are coming from the models themselves, so there's nothing you can do from the client to fix that.

It looks like we may be having an incident with those models at the moment, so my advice would be to try again later.

**Comment by mattt** [comment]
Follow up on this: We identified and resolved the underlying issue. If you try again, the model should produce output as expected now. If you're not seeing this, please let me know and I'll reopen and take another look.
