### ISSUE TITLE
Enable access to log probabilities

### ISSUE THREAD

**Issue by Andrea-de-Varda** [replicate/replicate-python#358]
## Feature Request

I am interested in obtaining log probabilities for the input tokens of my prompt and for the tokens that are produced by the models. Something like this can be achieved with Together:
```
client = Together(api_key=os.environ.get("TOGETHER_API_KEY"))
kwargs = {
    "engine": "mistralai/Mixtral-8x7B-Instruct-v0.1",
    "echo": True, # <---- this
    "logprobs": 1 # <---- and this
}
response = client.chat.completions.create(prompt="I love apples and oranges", **kwargs)
```
It can also be achieved with Fireworks:

```
url = "https://api.fireworks.ai/inference/v1/completions"
headers = {"Authorization": f"Bearer {api_key}"}
payload = {"model": "accounts/fireworks/models/mixtral-8x22b-instruct",
           "prompt":"I love apples and oranges",
           "logprobs": 2, # <---- this
           "echo": True   # <---- and this
}
response = requests.request("POST", url, json=payload, headers=headers)
```
In comparison, I am unable to achieve the same in the current `replicate-python` implementation.

**Relevance**
This feature would be extremely useful for me and many other users. I believe it's a simple feature to implement. Right now I can think of two main applications but I'm sure there are many more.

* **Multiple-choice selection:** If we can get token probabilities of the input, we can test the models on multiple choice problems and force the model to choose among specified alternatives. This is useful in many evaluations. 
* **Evaluation with soft metrics:** Sometimes it's useful to evaluate models not only with hard metrics like accuracy, F1 etc. but also with soft metrics based on log probabilities.

It would be really useful if the `replicate.run()` method had an argument like `echo` that if set to `true` and if also `logprobs` is set to true, it would return the tokens in input and the log probabilities of all the tokens in the prompt.

**Comment by mattt** [comment]
Hi @Andrea-de-Varda. Thanks for sharing your feedback. I agree that logprobs for input tokens are a useful feature to have. This client library calls Replicate's API, which in turn runs models hosted there, so adding support would require updating the models to support those additional parameters. However, I don't believe we have plans to support those parameters for the official language models Replicate hosts, like Mixtral.

**Comment by Andrea-de-Varda** [comment]
OK, thank you very much!
