### ISSUE TITLE
How to load images for training from local machine?

### ISSUE THREAD

**Issue by abdul7235** [replicate/replicate-python#360]
how can I input images from my local machine instead of a link?

training = replicate.trainings.create(
    model="stability-ai/sdxl",
    version="39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b",
    input={
      "input_images": "https://my-domain/training-images.zip",
      "token_string": "TOK",
      "caption_prefix": "a photo of TOK",
      "max_train_steps": 1000,
      "use_face_detection_instead": False
    },
    # You need to create a model on Replicate that will be the destination for the trained version.
    destination="your-username/model-name"
)

**Comment by abdul7235** [comment]
Thank you.

**Comment by abdul7235** [comment]
I have tried passing a handler to the zip file, but the training is failing. 

I get following message in logs:
Training failed.
input_images_filetype must be zip or tar

**Comment by mattt** [comment]
@abdul7235 The uploaded file is provided to the model with a presigned URL, which unfortunately breaks models with naïve file type checks. In the case of SDXL, it looks for a `.zip` suffix (which this URL won't have): 

https://github.com/replicate/cog-sdxl/blob/c79cb3c9c3c2968ee53ada00c7fb02aa3b9fc58c/preprocess.py#L80

As a workaround, you should be able to add `"input_images_filetype": "zip" to your training input.

https://github.com/replicate/cog-sdxl/blob/c79cb3c9c3c2968ee53ada00c7fb02aa3b9fc58c/train.py#L117

**Comment by abdul7235** [comment]
Thank you matt for your response.
I was able to solve it after a day long effort. 

Here is how I was able to send local zip file for training:

   with open(f"{filename.zip}", "rb") as file_input:
        encoded_data = base64.b64encode(file_input.read())


    encoded_data_str = encoded_data.decode('utf-8')

    


    training = replicate.trainings.create(
        model="stability-ai/sdxl",
        version="7762fd07cf82c948538e41f63f77d685e02b063e37e496e96eefd46c929f9bdc",
        input={
            "input_images": f"data:application/zip;base64,{encoded_data_str}",
            "token_string": "TOK",
            "caption_prefix": "a photo of TOK",
            "max_train_steps": 1000,
            "use_face_detection_instead": False
        },
        destination=f"{OWNER}/{model_name}"
    )
