### ISSUE TITLE
Pass generation parameters for models

### ISSUE THREAD

**Issue by jayhack** [replicate/replicate-python#39]
At the moment, there doesn't seem to be a way to modify parameters, e.g. `num_inference_steps` in `stable-diffusion`. The default has a low number of steps. Please help!

**Comment by barrylachapelle** [comment]
Are there any docs on parameters for each model anywhere Im missing? Im trying to pass some params to the BLIP model and cant quite figure out how to do so.

**Comment by mattt** [comment]
Hi @barrylachapelle. You can find the available inputs for a model from the API tab. https://replicate.com/salesforce/blip/api#inputs

**Comment by mattt** [comment]
@jayhack For [stability-ai/stable-diffusion](https://replicate.com/stability-ai/stable-diffusion), the default value for `num_inference_steps` is 50. You can configure a different value by specifying a `num_inference_steps` kwarg in the `predict` function.
