### ISSUE TITLE
Httpx time out with base64 encoded audio file.

### ISSUE THREAD

**Issue by Benniepie** [replicate/replicate-python#392]
Version 1.0.3

Replicate.run produces httpx time out with whisperx and base64 encoded audio file.

Version 0.34.2 

With this Version I get a 413 error that the audio file is too big.

I am able to run this manually via the website with the same file but not via Python and the API.

If the solution is to use a public URL for the audio file, then that's not going to happen. 

Any suggestions or a fix would be appreciated

**Comment by evilstreak** [comment]
You should be able to use data URIs of a few hundred KB, and replicate-python should handle uploads for you for files up to 100MB: https://replicate.com/docs/topics/predictions/input-files. Above that you'll need to provide a URL – if you're worried about privacy, we recommend using a signed URL so it's not default-by-public, and so you can revoke access after your prediction is complete.

How large is the file you're trying to send? Can you share the code you're using to call the replicate-python library?

**Comment by evilstreak** [comment]
I'm going to close this for now, but please reopen it with extra info if needed.
