### ISSUE TITLE
Command '['python', 'run.py', 'config/replicate.yml']' returned non-zero exit status 1."

### ISSUE THREAD

**Issue by starz222** [replicate/replicate-python#403]
Hi.  I'm having trouble with training.  I got this message: 
**Command '['python', 'run.py', 'config/replicate.yml']' returned non-zero exit status 1.**
Can anyone help solve this and get the training up and running?  Thanks so much, Steve.

**Comment by nickstenning** [comment]
Hi Steve, which model are you trying to train?
