### ISSUE TITLE
Document generating multiple images

### ISSUE THREAD

**Issue by kendallroth** [replicate/replicate-python#46]
Generating multiple images per prompt is ideal for comparison purposes, but does not seem supported. I am not sure whether this is just some models, or whether all Replicate models only generate a single output. However, it would be beneficial to have a documented approach to generating multiple images, as I am having trouble wading through attempts at such.

I first thought I could create multiple "background" predictions at the same time, but am not sure how to wait until they have all completed processing. Likely would involve the `wait()` function on all started predictions, but not sure how to go about this.

Is this a process that could be documented if already known? If not, could I get pointed in the right direction (if this is even possible)?

**Comment by mattt** [comment]
Hi @kendallroth. #193 added support for `async_run`, which makes it easy to generate a bunch of images in parallel and wait for them all to finish.

```python
import asyncio
import replicate

# https://replicate.com/stability-ai/sdxl
model_version = "stability-ai/sdxl:39ed52f2a78e934b3ba6e2a89f5b1c712de7dfea535525255b1aa35c5565e08b"
prompts = [
    f"A chariot pulled by a team of {count} rainbow unicorns"
    for count in ["two", "four", "six", "eight"]
]

async with asyncio.TaskGroup() as tg:
    tasks = [
        tg.create_task(replicate.async_run(model_version, input={"prompt": prompt}))
        for prompt in prompts
    ]

results = await asyncio.gather(*tasks)
print(results)
```

**Comment by kendallroth** [comment]
Thanks! I will admit I am no longer working with `replicate` anymore, but hope/trust that other will find this useful as well!
