### ISSUE TITLE
update usage to recommend hard-coding versions

### ISSUE THREAD

**Issue by zeke** [replicate/replicate-python#50]
We like to toss around this very simple usage, because it's so short and sweet:

```py
import replicate
model = replicate.models.get("some/model")
model.predict(prompt="...")
```

Unfortunately this invocation is inherently unstable: It fetches the latest version of the model behind the scenes, but what if a new version of the model is published that changes the inputs? Anyone using our happy-path example usage will now have a broken integration.

We should update the README to make it more clear that pinning to a specific version is safer:

```py
model = replicate.models.get("replicate/hello-world")
>>> version = model.versions.get("5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa")
>>> model.predict(text="python")
"hello python"
```

**Comment by bfirsh** [comment]
This has been done. This is probably the next thing: https://github.com/replicate/replicate-python/issues/69
