### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by codergautam** [replicate/replicate-python#62]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/66850133/212083758-4f29180f-614d-41cf-bc3d-91721d258805.png">

I am getting this error, Python 3.8

**Comment by Arshad9999** [comment]
What is the error message you are getting? It would be helpful to see the error message to understand what might be causing the issue. Additionally, providing more context such as the code you are running and any recent changes you made to your system would also be helpful in troubleshooting the issue.

**Comment by codergautam** [comment]
It wasn't related to Replicate, was related to UUID lib I was using. Fixed now.
