### ISSUE TITLE
Return file handles if it's a file

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate-python#67]
This should work:

```python
import replicate
from urllib.request import urlretrieve
model = replicate.models.get("stability-ai/stable-diffusion")
version = model.versions.get("27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478")
out = version.predict(prompt="wavy colorful abstract patterns, cgsociety"
background = Image.open(out)
```

See #48 #66

**Comment by RABIN360** [comment]
_আপনি কি বাড়ির নির্মাণ কাজের কথা ভাবছেন?
দক্ষ ঠিকাদার ও জনশক্তি খুঁজছেন?
আপনার স্বপ্নের বাড়িকে বাস্তবে রূপান্তরিত করতে, সুন্দর ও গুনগত মানের নিশ্চয়তা দিয়ে আমরা আছি আপনার পাশে।
WhatsApp
01626669802

1. [](https://www.facebook.com/Rayhanconstruction24/_)

**Comment by mattt** [comment]
This is solved by #348
