### ISSUE TITLE
Make it hard to not pin a version

### ISSUE THREAD

**Issue by bfirsh** [replicate/replicate-python#69]
The default way of running a prediction should be by selecting a version, not by selecting a model.

We should remove the `model.predict()` method, and something like this should be the recommended way to run predictions:

```
replicate.predict(version="27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478", input={...})
```

This might need syncing up with a future javascript client library. Something that @zeke might be thinking about.

**Comment by mattt** [comment]
I agree that the `predict()` method on models should be deprecated.

In the [Swift client](https://github.com/mattt/replicate-swift#usage), `createPrediction` is called on versions. The example usage I have in the README is `model.latest_version?.createPrediction(...)`.

For the purposes of demonstration, I think calling through `latest_version` strikes the right balance by signaling immutability / instability and not introducing too much friction. What do you think about recommending that in short form, and then following up in docs with a discussion about version pinning?

**Comment by zeke** [comment]
PRs in service of this:

- https://github.com/replicate/replicate-python/pull/70
- https://github.com/replicate/replicate-python/pull/71
- A forthcoming PR that removes references to `model.predict` on our website.

**Comment by zeke** [comment]
Reopening because there's still stuff to do around this.

**Comment by zeke** [comment]
@bfirsh @erbridge what if introduced support for a shorthand format for referencing a version?

So instead of:

```py
replicate.predict(version="27b93a2413e7f36cd83da926f3656280b2931564ff050bf9575f1fdf9bcd7478", input={...})
```

We could do:

```py
replicate.predict(version="stability-ai/stable-diffusion@27b93a", input={...})
```

This is nicer on the eyes and has the added benefit of making the model name discoverable.

Ben I know you're not keen on using abbreviated SHAs, but maybe in the case where you're scoping it to a specific model your concerns about it go away?

**Comment by zeke** [comment]
Actually this issue is done. We not only made it hard to pin a version. We made it impossible. ✅ 

Moving the conversation about API design to a followup issue: https://github.com/replicate/replicate-python/issues/72
